app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: KuaiYun
publisher_url: https://github.com/KuaiYun
display_name: KuaiYun
executable_name: KuaiYun.exe
output_base_file_name: KuaiYun.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\KuaiYun"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - zh
script_template: inno_setup.sas
